#!/usr/bin/env bash
  #=================================================
  # Project: csb // ConzZah's-Shizuku-Bootstrapper
  # Author:  ConzZah / (c) 2025
  # Last Modification: 14.09.2025 / 23:24 [v0.1]
  #=================================================

pt="platform-tools"; ptl="$pt-latest-linux.zip"
shizuku="moe.shizuku.privileged.api"
s="== SUCCESS =="; f="xX FAILURE Xx"
shizuku_logo='
               .:::::::::::.
           .::=+####%######+=:-.
         .-+###################+=.@
       .-+#######################*+=%      
     .-+#######%@@@@@@@@@@@%#######*+:
    :+########%@-=+========@%########*-
   .%@@@@@%##%@=*#**#**###+=@%########*:
  *#@    @@@%@=****####*###*=@@%#####%#=@
  =@ .==:. @@=**#########*##*+%@%######*:@
  @ .=====. @@@@@@%####*#####*+#@%#%####-@ 
  ..=======:.... =@@@@@@@@@@##*+=%####%#-@
   ===...=======-......... @##*=@%%#%###-@ 
   :==.@.================: @#*=@@%%####*:@
  = ==:..===============:.@%+=@@#%%####+:@  
     ===========...-===:.@%=%@%%%%#%##*:@
      ==========.@@-===.@@=@@%%%#%%##*-@
        ========...-===. @@%%%#####*=:@
      @  .=============.@@%##%#%#*=:@
        @   ==========- @######*=:@@
              =========..@##*=--:@
              @ . v0.1 :: @+--:@@
'; echo -e "$shizuku_logo\n    == ConzZah's-Shizuku-Bootstrapper ==\n"
connect2device () {
## waits for a device to connect
echo -e "--> STARTING ADB..\n"
adb start-server >/dev/null && \
echo -e "--> WAITING FOR DEVICE TO CONNECT..\n"; dev=""
until [ -n "$dev" ]; do adb wait-for-device >/dev/null
sleep 0.7; dev="$(adb get-serialno | head -n1)"
done
echo -e "--> FOUND DEVICE: $dev <--"
## get the devices architecture:
dev_arch="$(adb shell /system/bin/uname -m)"
[ "$dev_arch" = "aarch64" ] &&  dev_arch="arm64"
[ "$dev_arch" = "armv7l" ] && dev_arch="arm"
}

start_shizuku () {
## starts shizuku
shizuku_codepath="$(echo "$local_shizuku" | grep -o 'codePath.*'| cut -d '=' -f 2-)"
adb shell "$shizuku_codepath/lib/$dev_arch/libshizuku.so" && \
[ "$d" = "s"  ] && return "$?" || \
echo -e "\n$s\n" || echo -e "\n$f\n" && exit "$?"
}

dl_shizuku () {
## downloads the latest apk if shizuku is missing
## fetch apk version string
apk="$(curl -sL "https://apt.izzysoft.de/fdroid/index/apk/$shizuku" | head -69| \
grep "moe.*.apk"| cut -d "'" -f 4| cut -d / -f 4)"
## download & install shizuku
[ ! -f "$apk" ] && echo -e "\n--> DOWNLOADING SHIZUKU..\n" && \
curl -#LO "https://apt.izzysoft.de/fdroid/repo/$apk"
[ -z "$x" ] && echo -e "\n--> INSTALLING SHIZUKU..\n" && \
adb install "$apk" && rm "$apk" && check4shizuku
}

check4adb () {
## if adb is not installed, download platform-tools
[ -z "$x" ] && command -v adb >/dev/null && return 0 ||
echo -e "--> DOWNLOADING ${pt^^}..\n" && \
{ curl -#LO "https://dl.google.com/android/repository/$ptl" && echo "" || exit 1
command -v unzip >/dev/null && unzip -o "$ptl" && rm -f "$ptl" && cd "$pt" || exit 1
platform_tools="adb fastboot sqlite3 etc1tool hprof-conv mke2fs make_f2fs make_f2fs_casefold"
echo -e "\n--> INSTALLING ${pt^^}..\n"
for tool in $platform_tools; do
! command -v "$tool" >/dev/null && \
sudo install "$tool" /usr/bin; done
[ ! -f "/usr/lib64/libc++.so" ] && cp -f lib64/libc++.so /usr/lib64
[ -z "$x" ] && cd .. && rm -rf "$pt" && echo -e "\n--> INSTALLED ${pt^^}." ;}
}

check4shizuku () {
## checks for existing shizuku install
echo -e "\n--> CHECKING IF SHIZUKU IS INSTALLED..\n"
local_shizuku=""; local_shizuku="$([ -n "$dev" ] && adb shell "dumpsys package packages"| grep "$shizuku")"
[ -z "$local_shizuku" ] && { dl_shizuku && start_shizuku ;}
[ -n "$local_shizuku" ] && echo -e "--> SHIZUKU FOUND, STARTING..\n" && \
start_shizuku ;}

## demonic stuff
daemon () { echo -e "--> DAEMON SPAWNED.\n"; until [ "$x" != "$x" ]; do
{ check4adb >/dev/null; connect2device >/dev/null; check4shizuku >/dev/null; sleep 5 ;} done ;}

kill_daemon () { pkill -Af "csb -d" && echo -e "--> OLD DAEMONS KILLED.\n" && return 0 || echo -e "--> NO DAEMONS RUNNING.\n" && return 0 ;}

#### LAUNCH #### LAUNCH #### LAUNCH #### LAUNCH #### LAUNCH #### LAUNCH #### LAUNCH ####
[ -z "$1" ] && { check4adb; connect2device; check4shizuku; exit "$?" ;} ## <-- if launched without args
[ "$1" = "-apk" ] && { x="y" && dl_shizuku && exit "$?" ;} ## <-- for when one only wants to download the apk
[ "$1" = "-adb" ] && { x="y" && check4adb && exit "$?" ;} ## <-- for when one only wants adb
[ "$1" = "-kd" ] && { d="k"; kill_daemon; exit "$?" ;}
[ "$1" = "-d" ] && d="s" && { kill_daemon; echo -e "--> SPAWNING DAEMON..\n" && daemon >/dev/null & exit ;}
[ -z "$1" ] || [ -n "$1" ] || [ "$1" = "-h" ] && echo -e "USAGE: bash csb [OPTION]\n\nOPTIONS:\n\n-d\t\tAWAKES THE DAEMON\n-kd\t\tKILLS ALL RUNNING DAEMONS\n-apk\t\tDOWNLOADS THE LATEST SHIZUKU APK\n-adb\t\tDOWNLOADS ${pt^^}\n"
#### LAUNCH #### LAUNCH #### LAUNCH #### LAUNCH #### LAUNCH #### LAUNCH #### LAUNCH ####
